[alias]
test_tuples = "cargo test --test cucumber -- -t '@tuples' --fail-fast"
test_canvases = "cargo test --test cucumber -- -t '@canvases' --fail-fast"
test_matrices = "cargo test --test cucumber -- -t '@matrices' --fail-fast"
test_transformations = "cargo test --test cucumber -- -t '@transformations' --fail-fast"
